export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as NotFound } from './404/NotFound'
export { default as Main } from './main/Main'
export { default as Sidebar } from './sidebar/Sidebar'